;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="LightCombo",NewTagName="LightInput")
+GameplayTagRedirects=(OldTagName="HeavyInput",NewTagName="ComboInput")
+GameplayTagRedirects=(OldTagName="LightInput",NewTagName="LightAttackInput")
+GameplayTagRedirects=(OldTagName="ComboInput",NewTagName="HeavyAttackInput")
+GameplayTagRedirects=(OldTagName="CombatMove.Heavy.1",NewTagName="CombatMove.Heavy.WallBounce")
+GameplayTagRedirects=(OldTagName="InputTag",NewTagName="CombatInputTag")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="BloodlustReady",DevComment="")
+GameplayTagList=(Tag="CombatInputTag",DevComment="")
+GameplayTagList=(Tag="CombatInputTag.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="CombatInputTag.LightAttack",DevComment="")
+GameplayTagList=(Tag="CombatMove",DevComment="Base Combat move for all weapons")
+GameplayTagList=(Tag="CombatMove.Heavy",DevComment="")
+GameplayTagList=(Tag="CombatMove.Heavy.HelmBreaker",DevComment="")
+GameplayTagList=(Tag="CombatMove.Heavy.Launcher",DevComment="")
+GameplayTagList=(Tag="CombatMove.Heavy.WallBounce",DevComment="")
+GameplayTagList=(Tag="CombatMove.Idle",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.1",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.2",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.3",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.4",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.5",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.Air",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.Air.1",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.Air.2",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.Air.3",DevComment="")
+GameplayTagList=(Tag="CombatMove.Light.Air1.1",DevComment="")
+GameplayTagList=(Tag="HeavyAttackInput",DevComment="")
+GameplayTagList=(Tag="LightAttackInput",DevComment="")
+GameplayTagList=(Tag="State",DevComment="")
+GameplayTagList=(Tag="State.Player",DevComment="")
+GameplayTagList=(Tag="State.Player.Airborne",DevComment="")
+GameplayTagList=(Tag="State.Player.AirCombo",DevComment="")
+GameplayTagList=(Tag="State.Player.Grounded",DevComment="")

